extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
env:
  browser: true
  es2020: true
plugins: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-shadow: off
  comma-dangle: off
  radix: off
  no-use-before-define: off
  no-constant-condition: off
  no-unused-vars: off
  no-await-in-loop: off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
      caughtErrorsIgnorePattern: ^_
      destructuredArrayIgnorePattern: ^_
